### ISSUE TITLE
Rename project to vgeoip and make it private

### ISSUE THREAD

**Issue by ignatiusreza** [voyagin/freegeoip#2]
After this got released to GCP, the one in heroku private becomes obsolete, and subsequently, voyagin/vgeoip also becomes obsolete..

Since we'll modify this repo in ways that might include private information (deployment key, etc), we should make this repo private.. and rename to vgeoip just for fun.. :stuck_out_tongue_closed_eyes:

**Comment by saveav** [comment]
agree 😄

**Comment by saveav** [comment]
closed, not renamed 👯
